# -*- coding: utf-8 -*-
"""Copy of DL_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WExbsWq9cZxbUmYhhb6QxepVGmA2uaPm
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import warnings

warnings.filterwarnings('ignore')

HouseDF = pd.read_csv('/content/USA_Housing.csv')

HouseDF.head()

HouseDF.info()

HouseDF.describe()

HouseDF.columns

sns.pairplot(HouseDF)

sns.distplot(HouseDF['Price'])

sns.heatmap(HouseDF.drop('Address',axis=1).corr(), annot=True)

X = HouseDF[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
               'Avg. Area Number of Bedrooms', 'Area Population']]

y = HouseDF['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

lm = LinearRegression()

lm.fit(X_train,y_train)

print(lm.intercept_)

coeff_df = pd.DataFrame(lm.coef_,X.columns,columns=['Coefficient'])
coeff_df

predictions = lm.predict(X_test)

plt.scatter(y_test,predictions)

sns.distplot((y_test-predictions),bins=50)

print('MAE:', metrics.mean_absolute_error(y_test, predictions))
print('MSE:', metrics.mean_squared_error(y_test, predictions))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, predictions)))

import pandas as pd
# Take user input
income = float(input("Enter Avg. Area Income: "))
age = float(input("Enter Avg. Area House Age: "))
rooms = float(input("Enter Avg. Area Number of Rooms: "))
bedrooms = float(input("Enter Avg. Area Number of Bedrooms: "))
population = float(input("Enter Area Population: "))

# Create DataFrame with EXACT column names
manual_data = pd.DataFrame({
    'Avg. Area Income': [income],
    'Avg. Area House Age': [age],
    'Avg. Area Number of Rooms': [rooms],
    'Avg. Area Number of Bedrooms': [bedrooms],
    'Area Population': [population]
})

# Predict price
predicted_price = lm.predict(manual_data)

print("\nEstimated House Price: $", round(predicted_price[0], 2))# 79545.458574	5.682861  7.009188	4.09  23086.800503