# -*- coding: utf-8 -*-
"""DL_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKucJaJcm8CuPfHQoDgxMDnb6qp71ggE
"""



import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Load Data
(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words=10000)
input_train = sequence.pad_sequences(input_train, maxlen=200)
input_test  = sequence.pad_sequences(input_test,  maxlen=200)

# LSTM Model
model1 = Sequential([
    Embedding(10000, 128),
    LSTM(128, dropout=0.2, recurrent_dropout=0.2),
    Dense(1, activation='sigmoid')
])
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train & Evaluate
model1.fit(input_train, y_train, batch_size=32, epochs=5,
          validation_data=(input_test, y_test))

score, acc = model1.evaluate(input_test, y_test, batch_size=32)
print(f'Test Accuracy: {acc:.4f}')

# Predict one sample
sample  = input_test[0].reshape(1, -1)
pred    = model1.predict(sample)
print("Positive" if pred > 0.5 else "Negative")

#==========================4th CNN MRI==============================

import tensorflow as tf
from tensorflow.keras import layers, models, optimizers

# Load & Normalize
(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()
train_images, test_images = train_images / 255.0, test_images / 255.0

# Hyperparameters
LEARNING_RATE = 0.001
FILTER_SIZE   = (3, 3)
DROPOUT_RATE  = 0.3
OPTIMIZER     = optimizers.Adam(learning_rate=LEARNING_RATE)

# Build CNN
model = models.Sequential([
    layers.Conv2D(32, FILTER_SIZE, activation='relu', input_shape=(32, 32, 3)),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, FILTER_SIZE, activation='relu'),
    layers.Dropout(DROPOUT_RATE),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, FILTER_SIZE, activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10)    # 10 classes
])

# Compile & Train
model.compile(optimizer=OPTIMIZER,
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=10,
                    validation_data=(test_images, test_labels))

score,acc= model.evaluate(test_images, test_labels)
print('score: ',score, "Accuracy: ",acc)

score,acc= model.evaluate(test_images, test_labels)
print('score: ',score, "Accuracy: ",acc)

#=========================5th------rnn----------
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Step 1: Reviews + Labels (added training data!)
reviews = [
    "I absolutely love this product, it's amazing!",
    "This is the worst service I have ever had.",
    "It's okay, but could be much better.",
    "Fantastic experience, highly recommend!",
    "Terrible quality, never buying again.",
    "Pretty good, I enjoyed it overall.",
    "Best purchase ever, totally worth it!",
    "Awful product, complete waste of money.",
    "Really happy with this, works perfectly!",
    "Disappointed, expected much better quality."
]
labels = [1, 0, 0, 1, 0, 1, 1, 0, 1, 0]   # 1=Positive, 0=Negative

# Step 2: Tokenize & Pad
vocab_size = 1000
max_length = 20

tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(reviews)
sequences = tokenizer.texts_to_sequences(reviews)
padded    = pad_sequences(sequences, maxlen=max_length, padding='post')

# Step 3: GRU Model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 16),
    tf.keras.layers.GRU(32),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Step 4: Train (NOW it learns!)
model.fit(padded, np.array(labels), epochs=50, verbose=0)
print("Training Done!")

# Step 5: Predict
predictions = model.predict(padded)

# Step 6: Build Network Graph
G = nx.Graph()
for i, review in enumerate(reviews):
    score     = float(predictions[i][0])
    sentiment = "Positive" if score > 0.5 else "Negative"
    G.add_node(i+1, text=review[:30], sentiment=sentiment, score=score)

# Connect same-sentiment nodes
nodes = list(G.nodes(data=True))
for i in range(len(nodes)):
    for j in range(i+1, len(nodes)):
        if nodes[i][1]['sentiment'] == nodes[j][1]['sentiment']:
            G.add_edge(nodes[i][0], nodes[j][0])

# Step 7: Draw Graph
colors = ['#2ecc71' if G.nodes[n]['sentiment'] == 'Positive'
          else '#e74c3c' for n in G.nodes]

pos = nx.spring_layout(G, seed=42)
plt.figure(figsize=(10, 6))
nx.draw(G, pos, node_color=colors, node_size=1500,
        labels={n: f"R{n}\n{G.nodes[n]['sentiment']}" for n in G.nodes},
        font_size=8, font_color='white', font_weight='bold', edge_color='gray')
plt.title("Sentiment Network Graph | Green=Positive  Red=Negative")
plt.show()

# Step 8: Print Results
for node, data in G.nodes(data=True):
    print(f"Node {node} | {data['sentiment']} ({data['score']:.2f}) | {data['text']}")

# New Predictions (without separate padding step)
new_reviews = ["This product is wonderful!", "Horrible experience!", "Its okay not bad."]

for review in new_reviews:
    seq    = tokenizer.texts_to_sequences([review])
    pred   = model.predict(pad_sequences(seq, maxlen=20, padding='post'), verbose=0)
    print(f"{review} → {'Positive 😊' if pred[0][0] > 0.6 else 'Negative 😞'} ({pred[0][0]:.2f})")

